fix: defer getting a reference to 'SequencerCommon' keymap_items
On startup blender would complain that from QTERemoveKeyMapItem:

```
KeyError: 'bpy_prop_collection[key]: key "SequencerCommon" not found'
```

The reference to keymap_items, which QTERemoveKeyMapItem needed to remove the
keymap item by id, is now fetched on demand the first time the operator to
remove a kepmap item is called.